const message = {
  SERVER_START_MESSEGE: 'server is running on port:',
  REGISTER_DATA: 'REGISTERED',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  LOGGED_IN: 'LOGGED_IN SUCCESSFULLY',
  INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
  SUCCESSFULLY_NEW_CODE_CREATED: 'SUCCESSFULLY_NEW_CODE_CREATED',
  FAILED_TO_CREATE_NEW_CODE: 'FAILED_TO_CREATE_NEW_CODE',
  SUCCESSFULLY_NEW_CODE_UPDATED: 'SUCCESSFULLY_NEW_CODE_UPDATED',
  FAILED_TO_UPDATE_NEW_CODE: 'FAILED_TO_UPDATE_NEW_CODE',
  SUCCESSFULLY_GET_CODE_VERSION_DETAILS: 'SUCCESSFULLY_GET_CODE_VERSION_DETAILS',
  FAILED_TO_GET_CODE_VERSION_DETAILS: 'FAILED_TO_GET_CODE_VERSION_DETAILS',
  SUCCESSFULLY_DELETED_CODE_VERSION_DETAILS: 'SUCCESSFULLY_DELETED_CODE_VERSION_DETAILS',
  FAILED_TO_DELETE_CODE_VERSION_DETAILS: 'FAILED_TO_DELETE_CODE_VERSION_DETAILS',
  SUCCESSFULLY_JOINED_NEW_USER_IN_CODE: 'SUCCESSFULLY_JOINED_NEW_USER_IN_CODE',
  FAILED_TO_JOIN_NEW_USER_IN_CODE: 'FAILED_TO_JOIN_NEW_USER_IN_CODE',
  SUCCESSFULLY_LEAVED_CODE: 'SUCCESSFULLY_LEAVED_CODE',
  FAILED_TO_LEAVE_CODE: 'FAILED_TO_LEAVE_CODE',
  SUCCESSFULLY_GET_USER_CHAT_DETAILS: 'SUCCESSFULLY_GET_USER_CHAT_DETAILS',
  FAILED_TO_GET_USER_CHAT_DETAILS: 'FAILED_TO_GET_USER_CHAT_DETAILS',
};

module.exports = message;
